imports:
  - { resource: ../common.yml }

services:
  btipay.payment_flow.service:
    class: BTiPay\Service\Payment\PaymentFlowService
    public: true
    arguments:
      - '@btipay.config'
      - '@btipay.facade.context'
      - '@btipay.logger'
      - '@btipay.order.command'
      - '@btipay.authorize.command'
      - '@btipay.validator.availability'

  btipay.return_flow.service:
    class: BTiPay\Service\Payment\ReturnFlowService
    public: true
    arguments:
      - '@btipay.payment_repository'
      - '@btipay.facade.context'
      - '@btipay.payment_details.command'

  btipay.account_flow.service:
    class: BTiPay\Service\Account\AccountFlowService
    public: true
    arguments:
      - '@btipay.config'
      - '@btipay.card_repository'
      - '@btipay.facade.context'
      - '@btipay.card.service'
      - '@btipay.payment_details.service'
      - '@btipay.logger'

  btipay.webhook_flow.service:
    class: BTiPay\Service\Webhook\WebhookFlowService
    public: true
    arguments:
      - '@btipay.webhook.service'
      - '@btipay.logger'
      - '@btipay.config'

  btipay.authorize.command:
    class: BTiPay\Command\ActionCommand
    public: true
    arguments:
      - 'authorize'
      - '@btipay.order.request'
      - '@BTiPay\Client\BtpayClient'
      - '@btipay.logger'
      - '@btipay.config'
      - '@btipay.common.response.validator'
      - '@btipay.order.response.handler'

  btipay.order.command:
    class: BTiPay\Command\ActionCommand
    public: true
    arguments:
      - 'order'
      - '@btipay.order.request'
      - '@BTiPay\Client\BtpayClient'
      - '@btipay.logger'
      - '@btipay.config'
      - '@btipay.common.response.validator'
      - '@btipay.order.response.handler'

  btipay.order.request:
    class: BTiPay\Request\BuilderComposite
    public: true
    arguments:
      - '@btipay.pst_map_factory'
      - [
        'BTiPay\Request\OrderRequestBuilder',
        'BTiPay\Request\OrderBundleRequestBuilder',
        'BTiPay\Request\CustomerRequestBuilder',
        '@btipay.save_card.request',
        'BTiPay\Request\AdditionalParametersBuilder']

  btipay.request.builder.composite:
    class: BTiPay\Request\BuilderComposite
    public: true
    arguments:
      - '@btipay.pst_map_factory'

  btipay.save_card.request:
    class: BTiPay\Request\SaveCardsRequestBuilder
    public: true
    arguments: [ '@btipay.card_repository' ]

  btipay.order.response.handler:
    class: BTiPay\Response\HandlerChain
    public: true
    arguments:
      - '@btipay.pst_map_factory'
      - [ '@btipay.save_transaction_handler' ]

  btipay.save_transaction_handler:
    class: BTiPay\Response\SaveTransactionHandler
    public: true
    arguments: [ '@btipay.payment_repository' ]
