btipay_api_payment_handle:
  path: /api/payment/handle/{action}/{orderId}
  methods: [POST]
  defaults:
    _controller: 'BTiPay\Controller\ApiPaymentController::handleRequest'
  requirements:
    action: 'capture|refund|cancel'
    orderId: '\d+'
